Feature/3
618knot/SODH_2023_CIeaST pull request #5
Opened 2023-11-03 09:48 UTC by kiryu-3

#3 
CRUD処理を関数化してみました。
appフォルダ内の2つのsqlite_util.pyを編集した感じです。
コメントお願いします。

2023-11-03 10:13 UTC, 618knot requested changes
ありがとう:star:
複数指摘があります～
- 動作確認はしましたか？
    - おそらくこのままだと動かないです、今後は最低限動く状態にしてからPRを作ってほしいです
    - 若干後出しじゃんけんで申し訳ないけど、FastAPIの挙動確認を兼ねて`demo_users.py`の実装を今回実装した関数に置き換えて正常に動くか確認してみてください(それも一緒にpushしちゃって大丈夫です)

2023-11-03 10:13 UTC, 618knot commented on app/migrations/util/sqlite_util.py
テーブル定義をいじるのがmigrations下のファイルの役割の想定でいるので、こっちのファイルには今回の関数の実装は必要ないです。
取り消しておいてもらえるとありがたいです。

2023-11-03 10:13 UTC, 618knot commented on app/routers/util/sqlite_util.py
> +    if data:
executemanyだけで1レコードから複数レコードの操作までできる気がします
分岐の必要はないかも

2023-11-03 10:18 UTC, 618knot commented
あと、PRの頭にissue番号書いてくれてありがとう
今回は大丈夫だけど

close #3
みたいな感じで書いておくと、PRが閉じたときにissueも一緒に閉じてくれるので便利です

2023-11-04 10:45 UTC, kiryu-3 commented
ローカル環境でCRUD処理が動く程度には、routers内の関数を修正しました。
demo_users.py内も関数に合わせて編集しています。

Docker環境内で動かそうとすると、ルートディレクトリ直下に`DB_NAME=my_database.db`と記述したenvファイルを置いているのですがこの部分でエラーが出ます。
（ちょっとコメント以降忙しくてコメントの返信遅くなると思いますが）コメントお願いします。

![image](https://github.com/618knot/SODH_2023_CIeaST/assets/84606676/75b70075-a3f5-472f-9e9b-7dc075eba3af)

2023-11-05 01:43 UTC, 618knot approved these changes
動作問題なしです💯 

dockerで動かない問題のほうは、`app`直下に.envを置いてもらえれば解決すると思います。(コンテナ内にはappフォルダの中身しかコピーされないようにしてある)
![image](https://github.com/618knot/SODH_2023_CIeaST/assets/82982400/3b5b6ca1-f699-4e26-86c7-4b308f6d9d43)

2023-11-05 01:45 UTC, merged